spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/spring2?useUnicode=true&characterEncoding=utf8&useSSL=false
    password: root
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 6003