spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rappers
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
#  flyway:
#    enabled: true
server:
  port: 8081





